os: unstable

environment:
  matrix:
    - nodejs_version: 8.4

platform:
  - x64

cache:
  - node_modules -> package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run package

artifacts:
  - path: release
    name: release

before_deploy:
  - python --version
  - pip --version
  - pip install gsutil

deploy_script:
  # - ps: gsutil cp release/*.nsis gs://morpheo_analytics
  - ps: ls release
